CREATE TABLE PAGE_TBL
(
PAGE_ID          int(11)      	NOT NULL  primary key,         
PAGE_TITLE       varchar(500)   NOT NULL,           
PAGE_PARAGRAPH1  varchar(500)   NOT NULL,           
PAGE_PARAGRAPH2  varchar(500)   NOT NULL           
);

INSERT INTO PAGE_TBL VALUES (0,'A road in the middle of nowhere','Off in the distance there were explosions in the sky.','My cell lost reception.');
INSERT INTO PAGE_TBL VALUES (1,'In a Cluttered Storage Closet','It was dark in there.','Stuff scattered everywhere -- mostly junk.');
INSERT INTO PAGE_TBL VALUES (2,'Outside Sid\'s Diner','Red clouds streamed overhead.','Explosions thudded off in the distance.');
INSERT INTO PAGE_TBL VALUES (3,'A Diner in the Middle of Nowhere','Time was ticking.','Had to make a move.');
INSERT INTO PAGE_TBL VALUES (4,'Leaving Sid\'s Diner In Your Truck','I left that place in the dust.','Had to decide where to go next. ');
INSERT INTO PAGE_TBL VALUES (5,'Interrogating A Looter','I remember glancing under that hood and realizing he was younger than I thought. Didn\'t have much to say.','He insisted he was looking to feed his family. I told him I didn\'t bust him in the KITCHEN.');
INSERT INTO PAGE_TBL VALUES (6,'Pursuing the man down the road','The man just kept hurrying away from me.','Mumbled crazy things. He wasn\'t right in the head.');
INSERT INTO PAGE_TBL VALUES (7,'Feeding a Stray Dog','I opened a can of meat and threw it away from the man.','The thing finished it off, then circled my truck. Took a shine to me.');
INSERT INTO PAGE_TBL VALUES (8,'A Diner in the Middle of Nowhere','I told him I had room in my truck.','And that we had strength in numbers. He agreed.');
INSERT INTO PAGE_TBL VALUES (9,'The Greensburg Outskirts','The place looked nearly deserted.','Had a feeling I should hurry.');
INSERT INTO PAGE_TBL VALUES (10,'The Greensburg Suburbs','Some of the houses already looked trashed.','I heard glass break in a backyard as I drove past.');
INSERT INTO PAGE_TBL VALUES (11,'In a Recently Abandoned House','The TV was still on. ','Someone had left it on the emergency broadcast station.');
INSERT INTO PAGE_TBL VALUES (12,'Stopped at a Police Checkpoint','Two cops BLOCKED the road into Greensburg. Weren\'t letting anybody in -- only out. ','CIVIL EMERGENCY. MANDATORY EVACUATION. Proceed to the evac center at the airport.');
INSERT INTO PAGE_TBL VALUES (13,'Approaching the Airport','Could see military trucks down there. ','Crowds of people near the doors.');
INSERT INTO PAGE_TBL VALUES (14,'In an Airport Terminal Shelter','Stank like people in there. Lots of them burned pretty badly. Some of them bodies. ','A group of people had gathered in a corner, talking.');
INSERT INTO PAGE_TBL VALUES (15,'Inside A Secure Terminal','The army had set up a base in one of the airport terminals.','Lots of soldiers. Lots of gas masks. They knew what was coming.');
INSERT INTO PAGE_TBL VALUES (16,'Demanding info from Clyde','I told him to tell me JUST WHAT WAS GOING ON.','He told me to find a GAS MASK or respirator and to do it FAST. He\'d seen LOTS of bodies already.');
INSERT INTO PAGE_TBL VALUES (17,'A crowd of talking people','Away from all the sick people, a crowd had formed.','They traded gear and talked about what to do.');
INSERT INTO PAGE_TBL VALUES (18,'In Someone\'s Back Yard','A guy in a HOODIE had broken in and was running out the back door. ','For a split second we locked eyes.');
INSERT INTO PAGE_TBL VALUES (19,'Disaster in the airport terminal','Then the glass in the terminal BLEW IN -- crash like thunder.','wind, and the place started to fill with gas.');
INSERT INTO PAGE_TBL VALUES (20,'Gas Wastes Near the Airport','The survivors from the airport scattered out into the thick of it. ','Could feel it burnin\' my skin. Breathed through the mask.');
INSERT INTO PAGE_TBL VALUES (21,'Gas Wastes Near the Airport','The survivors from the airport scattered out into the thick of it. ','Had nothing to protect myself. Burned my skin. It burned my lungs.');
INSERT INTO PAGE_TBL VALUES (22,'Bones in A Chemical Wasteland','The gas SEARED THE SKIN from my body. My bones were scoured clean.','And YET, while my remains BLEACHED IN THE SUN, no animals came.');
INSERT INTO PAGE_TBL VALUES (23,'Bones in the wasteland','The sun beat down --','and no animals came.');
INSERT INTO PAGE_TBL VALUES (24,'Edge of a Gas-Filled Gully','Three people were trapped down there. Could really only make out the one in front.','The gas streamed like a river. Was broilin\' them alive.');
INSERT INTO PAGE_TBL VALUES (25,'Bitten by an angry dog','The damn thing turned on me and snapped my arm.','The old guy started runnin\' away. Didn\'t seem right in the head.');
INSERT INTO PAGE_TBL VALUES (26,'In a plastic-wrapped shelter','We used all the sheeting we could find and tried to seal the room.','As the storm howled outside, kirk pulled out a cell phone and stared at it sadly.');
INSERT INTO PAGE_TBL VALUES (27,'New Page','','');
INSERT INTO PAGE_TBL VALUES (28,'Denied Entry in the Parking Lot','They said they weren\'t in the business of sheltering civilians.','Told me to keep on walking.');
INSERT INTO PAGE_TBL VALUES (29,'Outside Fort Eisenhower','I walked for another three hours down that road.','It led us to soldiers. ');
INSERT INTO PAGE_TBL VALUES (30,'A Shelter in the Mountain','The army was filing people into a long line.','Explosions in the distance. Their guns scanned the sky.');
INSERT INTO PAGE_TBL VALUES (31,'Landing at a mountain airstrip','We were in the air for only fifteen minutes.','From where we landed, people were ferried in troop carriers.');
INSERT INTO PAGE_TBL VALUES (32,'In Line at the Mountain Shelter','Two assholes in line were arguing with a soldier in front of me.','I tried to push by, but they blocked my way.');
INSERT INTO PAGE_TBL VALUES (33,'Outside a closed Restaurant','The windows were papered up but I could see movement inside.','Couldn\'t cross the lot -- I spotted a rifle poking through an open window.');
INSERT INTO PAGE_TBL VALUES (34,'Rushing through the Gas Wastes','Could feel all my skin blistering. The gas left a residue on everything.','Huffed through the mask. ');
INSERT INTO PAGE_TBL VALUES (35,'Down the End of a Barrel','The guy was waiting for me around the corner.','Looked old enough to be retired. Not a real cop.');
INSERT INTO PAGE_TBL VALUES (36,'Rummaging through the house','I took ten and searched through their rooms.','Bingo.');
INSERT INTO PAGE_TBL VALUES (37,'Down the End of a Barrel','Turns out Clyde was kind of a scumbag himself. He took the watch and said I had BALLS.','He said if that was my WORKING TRUCK out front, he INSISTED we leave greensburg TOGETHER.');
INSERT INTO PAGE_TBL VALUES (38,'Buying Gear from Charlie','He said if I had the cash, he had a gas mask to spare. Some tape, too.','Said he was prepared for this. Knew it was gonna happen soon.');
INSERT INTO PAGE_TBL VALUES (39,'Trading with Charlie Burns','He held out the gas mask and wagged it at me.','I was relieved to have it. Started to think I\'d need it soon.');
INSERT INTO PAGE_TBL VALUES (40,'Trading with Charlie Burns','He grinned, counting through the cash.','He said he hoped it helped me out.');
INSERT INTO PAGE_TBL VALUES (41,'Watching Sid talk to the cops','Sid told them that he was trying to get a hold of his BROTHER, MITCHELL. He was in the army.','They confirmed he wasn\'t at the airport.');
INSERT INTO PAGE_TBL VALUES (42,'Firing Ruthlessly on a Looter','I put few shots in him and he hit the floor.',' left him dead at the bottom of the stairs. His backpack was FULL OF USELESS JUNK.');
INSERT INTO PAGE_TBL VALUES (43,'Pulling Jeff Onto Solid Ground','He was going into shock. Wasn\'t sure if I could help him.','Was too hurt to follow me much further.');
INSERT INTO PAGE_TBL VALUES (44,'At a Shack in the Gas Wastes','Further on I found the road. ','But a storm was on the horizon. Needed shelter. There was a shack there.');
INSERT INTO PAGE_TBL VALUES (45,'Caught in a Toxic Storm','Hurricane Winds.','Could hardly walk. ');
INSERT INTO PAGE_TBL VALUES (46,'Taken by the Gas Storm','The wind dragged me over the wasteland. The gas ate me alive. ','No animals came.');
INSERT INTO PAGE_TBL VALUES (47,'Slowly rolling up to a shack','Luckily there was a break in the storm. The tape on the windows and vents was starting to give.','I needed the shelter.');
INSERT INTO PAGE_TBL VALUES (48,'Bones in the wasteland','My body was gnawed on by the gas for years.','and no animals came.');
INSERT INTO PAGE_TBL VALUES (49,'Snooping through the house','Turned some of the rooms upside down.','Couldn\'t find a thing.');
INSERT INTO PAGE_TBL VALUES (50,'Trying to Fix the Cruiser Radio','Wrestled with that damn radio for half an hour.','Never did get it working.');
INSERT INTO PAGE_TBL VALUES (51,'Digging through the closet','I rooted through that storage closet for too long.','Nothing.');
INSERT INTO PAGE_TBL VALUES (52,'Digging through the closet','Spent a few minutes looking around.','Turns out it wasn\'t all junk.');
INSERT INTO PAGE_TBL VALUES (53,'Driving through barren land','Looked like locusts had swarmed through and eaten everything green.','Drove for two hours like that. Then I saw someone on the road. ');
INSERT INTO PAGE_TBL VALUES (54,'Driving into Haggarsville','There had been a catastrophe there.','Toxic gas, they said. A storm of it. ');
INSERT INTO PAGE_TBL VALUES (55,'Ten Minutes in Haggarsville','The survivors had pulled what they had left together. ','One guy was ordering people around.');
INSERT INTO PAGE_TBL VALUES (56,'A Camp in the Woods','Big Wes guided me through the woods to a camp he knew about.','It was some kind of militia.');
INSERT INTO PAGE_TBL VALUES (57,'Empty Page','','');
INSERT INTO PAGE_TBL VALUES (58,'Standing over a downed man','I put one down and the others ran.','In his wallet was the name DAN KELLY. He was still breathing. ');
INSERT INTO PAGE_TBL VALUES (59,'Standing over Two Dead Men','Put two down, the other one got away. ','In one of their wallets was the name DAN KELLY. He was still breathing.');
INSERT INTO PAGE_TBL VALUES (60,'Intersecting Highway 76','To the left, the highway ran into the woods.','To the right, it ran to Fort Eisenhower -- still a ways off.');
INSERT INTO PAGE_TBL VALUES (61,'Dead End at a Country House','The road narrowed to an end.','There was a house -- door was closed, no movement inside.');
INSERT INTO PAGE_TBL VALUES (62,'In A Dense Forest','The path faded into nothing.','The leaves overhead hissed in the wind.');
INSERT INTO PAGE_TBL VALUES (63,'A Remote Helicopter Pad','The thing was completely surrounded by trees. ','The wind howled overhead.');
INSERT INTO PAGE_TBL VALUES (64,'Inside a Cramped Cockpit','The chopper lifted up into the air. ','Ned said he could get us to Greensburg or Fort Eisenhower.');
INSERT INTO PAGE_TBL VALUES (65,'Screeching to the Earth','We KEELED out of control and the GROUND RUSHED UP at us.','The ROTORS SCREAMED and the whole chopper SHOOK until the TERRIBLE IMPACT.');
INSERT INTO PAGE_TBL VALUES (66,'Approaching a Stranded Van','Someone waved a flag on top of the stopped van.','Coulda stopped if I had wanted to.');
INSERT INTO PAGE_TBL VALUES (67,'Pulled over at a Broken Van','They blew a tire, had no tools. ','The wind overhead howled. ');
INSERT INTO PAGE_TBL VALUES (68,'Reuniting Lost Brothers','Sid was glad to see his brother mitchell was alive. ','Sid said he would stay behind with them. Mitchell gave me a military radio to keep in touch.');
INSERT INTO PAGE_TBL VALUES (69,'An Abandoned Gas Station','Twenty minutes down the road and I needed gas.','Found a place. The Kiosk was locked but the pumps were running.');
INSERT INTO PAGE_TBL VALUES (70,'Holding Men at Gunpoint','I pumped the shotgun and burst out.','For one second, they froze.');
INSERT INTO PAGE_TBL VALUES (71,'A Grassy Hill with a View','Down the hill to the left was a woods.','Down the hill to the right the red clouds had killed all vegetation.');
INSERT INTO PAGE_TBL VALUES (72,'Inside A Gas Kiosk','Was digging around in there when I looked up and saw them.','Three of them. Armed.');
INSERT INTO PAGE_TBL VALUES (73,'Locked out of the Gas Kiosk','Couln\'t force the lock.','Had to give up and move on.');
INSERT INTO PAGE_TBL VALUES (74,'Searching the pumps','Found an old tire iron wedged in the side of one.','Nobody was gonna miss it.');
INSERT INTO PAGE_TBL VALUES (75,'Watching Your Truck Leave','I couldn\'t move fast enough. They got to my truck.','Shouldn\'t have left the keys inside. They fired it up and peeled out.');
INSERT INTO PAGE_TBL VALUES (76,'Running To Your Truck','Fired a few rounds and ran back to my truck.','Panted for breath. Wind howled overhead.');
INSERT INTO PAGE_TBL VALUES (77,'Chased Leaving the Gas Station','Another truck drove up behind me.','Ran me into a blocked onramp. Trapped.');
INSERT INTO PAGE_TBL VALUES (78,'A Desperate and Futile Sprint','I scrambled from the car, TOOK OFF down the road ON FOOT.','The SONNOVABITCH fired that pistol at my back. Deep-seeded burning pain in my chest. Fell to my knees. Bleeding. Bleeding.');
INSERT INTO PAGE_TBL VALUES (79,'Firing Rounds on the Highway','The guy on the back fell off.','Their truck sped away.');
INSERT INTO PAGE_TBL VALUES (80,'Firing Rounds on the Highway','The guy fell off the back.','While the truck was speeding off I shot the passenger too.');
INSERT INTO PAGE_TBL VALUES (81,'Telling MORGAN about DAN','She was SAD to hear things got violent.','Said she didn\'t need THIS anymore. Threw her ring in the truck.');
INSERT INTO PAGE_TBL VALUES (82,'Asking Morgan what happened','She said there were explosions and red gas. People got dizzy, threw up, SUFFOCATED. ','On top of it all, DAN KELLY and his no-good BROTHERS looted the pharmacy.');
INSERT INTO PAGE_TBL VALUES (83,'Asking about the Storm','She said there were HURRICANE winds and explosions. Most electronics stopped working.','And then POISON GAS. People shook to death. Their skin burned all up.');
INSERT INTO PAGE_TBL VALUES (84,'Shouting THIEF in the suburbs','I shouted THREE times and listened.','Silence, other than the sound of distant traffic.');
INSERT INTO PAGE_TBL VALUES (85,'Watching A Looter in the Window','There was someone lurking inside the house in a hoodie. ','I could see him filling a backpack.');
INSERT INTO PAGE_TBL VALUES (86,'Talking to Big Wes','Big Wes told me the Kellys BETRAYED this town when the gas hit.','He said DAN KELLY deserved to be cut down and laid out on the road. ');
INSERT INTO PAGE_TBL VALUES (87,'Swerving around the Barricade','Cranked the wheel and swerved around it.','Easy.');
INSERT INTO PAGE_TBL VALUES (88,'Losing Control of Your Slide','Cranked the wheel but the car slid out.','Thought that was it for me.');
INSERT INTO PAGE_TBL VALUES (89,'In the Wreck of Your Truck','One of them jumped off the back and looked in the broken window.','Couldn\'t turn my head to look.');
INSERT INTO PAGE_TBL VALUES (90,'Bones Outside Your Truck','Pulled me outta the truck and left me there. ','And no Animals came.');
INSERT INTO PAGE_TBL VALUES (91,'Murdering Dan Kelly','Told Dan that Big Wes says hello.','Then I let him have it.');
INSERT INTO PAGE_TBL VALUES (92,'Buying a Shotgun from Big Wes','Said if I used it against DAN KELLY, he had a 12 gauge for sale.','Came with a half dozen shells. ');
INSERT INTO PAGE_TBL VALUES (93,'Buying a MAP from Big Wes','Big Wes said I looked LOST. ','He offered to sell me an old map.');
INSERT INTO PAGE_TBL VALUES (94,'Bringing Dan Kelly to Morgan','She was SHOCKED to see him in such rough shape.','Said she had to FIND HELP for him and wanted to come WITH ME. She pleaded for the others to leave justice to the law.');
INSERT INTO PAGE_TBL VALUES (95,'Ten Minutes in Haggarsville','The survivors had pulled what they had left together. ','One guy was ordering people around.');
INSERT INTO PAGE_TBL VALUES (96,'Bringing Dan Kelly to Morgan','She was SHOCKED to see him in such rough shape.','Said she had to find help for him and wanted to come with me. She pleaded for the others to leave justice to the law.');
INSERT INTO PAGE_TBL VALUES (97,'Asking about the kellys','She said they were DRUG DEALERS and weren\'t scared of nobody.','She said they\'d been ROBBING on the roads. People wanted them dead, but morgan said Dan Kelly DESERVED BETTER.');
INSERT INTO PAGE_TBL VALUES (98,'Bringing Dan Kelly to Morgan','She was SHOCKED to see him in such rough shape.','Said she had to find help for him and wanted to come with me. She pleaded for the others to leave justice to the law.');
INSERT INTO PAGE_TBL VALUES (99,'Returning to Haggarsville','Stopped back in Haggarsville with DAN\'S BLOOD ON MY HANDS.','Big Wes said it was JUSTICE. Said I knew what was what. ');
INSERT INTO PAGE_TBL VALUES (100,'Telling MORGAN about DAN','She was SAD to hear things got violent.','Said she didn\'t need THIS anymore. Threw her ring in the truck.');
INSERT INTO PAGE_TBL VALUES (101,'Dead End at a Country House','Morgan BANGED on the door. She YELLED for NED.','There were FOOTSTEPS, and the door OPENED.');
INSERT INTO PAGE_TBL VALUES (102,'Dead End at a Country House','NED said a FRIEND of MORGANS was a FRIEND of HIS.','Said he knew of a CHOPPER in the woods and he could maybe get it off the ground with my help. ');
INSERT INTO PAGE_TBL VALUES (103,'Asking Ned about Shelter','He said we could go to Eisenhower or Greensburg, but NED didn\'t TRUST the GOVERNMENT.','said he wanted to go to his uncle\'s old SHELTER in the GROUND.');
INSERT INTO PAGE_TBL VALUES (104,'Asking Ned about Transport','Said he used to fly it for the CONSERVATION AUTHORITY.','Said he needed someone TECHNICAL to help get it into the air, but it COULD fly.');
INSERT INTO PAGE_TBL VALUES (105,'Offering to fix the chopper','Told NED I could help him get that chopper off the ground.','He seemed doubtful, but agreed to take us there. ');
INSERT INTO PAGE_TBL VALUES (106,'Collapsing In the Wilderness','Didn\'t take long to realize I was lost. As I walked further I felt sick. Nauseous.','It was getting to me. I HOWLED OUT and only my echo howled back.');
INSERT INTO PAGE_TBL VALUES (107,'Bones in the Wasteland','Collapsed on the ground, curled up in a ball.','And no Animals came.');
INSERT INTO PAGE_TBL VALUES (108,'Shouting to ned','I suggested we really think about where to go.','Ned said he was really only set on Eisenhower or Greensburg to get help for morgan.');
INSERT INTO PAGE_TBL VALUES (109,'Talking with Private Jakes','I walked up to the posted soldier.','He told me to take any wounded to a cot. DOCTORS will be around SHORTLY.');
INSERT INTO PAGE_TBL VALUES (110,'A Shady Deal in the Stairs','I passed him the WAD of CASH.','He ducked out and came back with the bottle of pills.');
INSERT INTO PAGE_TBL VALUES (111,'Talking Guns With Wes','I told him about when I used to RELOAD MY OWN SHELLS.','He told me I\'d be a help to the militia if I could find them.');
INSERT INTO PAGE_TBL VALUES (112,'Trapped in Your Truck','Sudden wind and the truck was swallowed up in a cloud.','Started coming through the vents.');
INSERT INTO PAGE_TBL VALUES (113,'In An Old Ransacked Building','Junk was heaped against one wall of the place.','The guy inside was frantic. His wife Jenny was still out there.');
INSERT INTO PAGE_TBL VALUES (114,'Final Panic in a Flood of Gas','As the storm HOWLED outside, the GAS SEEPED in through old panes and doors. ','It CORNERED me like a RAT in WATER and my SCREAMS were lost in the storm.');
INSERT INTO PAGE_TBL VALUES (115,'Crushed in a Hellish Wreck','I GUNNED it. The GAS STREAMED around me.','SUDDENLY I was clear and THE POLE WAS RIGHT THERE! TOO LATE TO BR--!');
INSERT INTO PAGE_TBL VALUES (116,'Near a Fight In Line','The BALD GUY took a swing at the soldier, climbed up on him.','The military fired shots into the area. People got hit.');
INSERT INTO PAGE_TBL VALUES (117,'Falling in a stampede','Then there were EXPLOSIONS and PLUMES of gas ROILED behind us.','People charged the gate like cattle and I was CRUSHED by the weight of their DESPERATE FEET.');
INSERT INTO PAGE_TBL VALUES (118,'Packed into a Shelter','Those of us that made it into the shelter huddled in the tunnels. ','We could hear explosions outside. Then the lights started to go out.');
INSERT INTO PAGE_TBL VALUES (119,'In the Dark at the End','The BULBS FLICKERED and EXPLOSIONS thundered outside. We were TRAPPED.','We huddled in a SCARED MASS until it grew quiet. Then slowly, in SHOCK, people began to REALIZE their LOSSES.');
INSERT INTO PAGE_TBL VALUES (120,'Rocky, tree-strewn Gas Wastes','Footing was sometimes impossible.','No sign of the road -- got turned around in the chaos.');
INSERT INTO PAGE_TBL VALUES (121,'Marshy Gas Wastes - Shot At','Someone was holed up in the building.','Rifle shots. Bullets crackled through the nearby brush.');
INSERT INTO PAGE_TBL VALUES (122,'Arrested in the Airport','Jakes overpowered me. Declared I was a TERRORIST.','Marched me through the crowd.');
INSERT INTO PAGE_TBL VALUES (123,'Over an Unconscious Soldier','Jakes was blacked out on the ground.','Had to move fast.');
INSERT INTO PAGE_TBL VALUES (124,'Disaster in the airport terminal','Then the glass in the terminal BLEW IN-- crash like thunder.','Hands bound -- I was trampled over and left for dead.');
INSERT INTO PAGE_TBL VALUES (125,'In an Airport Terminal Shelter','Stank like people in there. Lots of them burned pretty badly. Some of them bodies. ','A group of people had gathered in a corner, talking.');
INSERT INTO PAGE_TBL VALUES (126,'A crowd of talking people','Away from all the sick people, a crowd had formed.','They traded gear and talked about what to do.');
INSERT INTO PAGE_TBL VALUES (127,'At a Secure Laptop Station','There was a notebook locked to a table. ','I opened it up and hit some keys. It wanted a password.');
INSERT INTO PAGE_TBL VALUES (128,'At An Unattended Locker','There was a footlocker nearby and nobody at it.','I noticed that a soldier across the room started approaching me.');
INSERT INTO PAGE_TBL VALUES (129,'Searching For Useful Material','There was a crawlspace under the stairs. ','Found an old paint sheet.');
INSERT INTO PAGE_TBL VALUES (130,'Surrendering to Clyde','He waved the barrel and told me to get.','Said he\'d be reporting me to the police.');
INSERT INTO PAGE_TBL VALUES (131,'Hacking a Military Laptop','Took a few tense minutes, but I did it. ','Got past the password and into the operating system.');
INSERT INTO PAGE_TBL VALUES (132,'Printing an Airplane Ticket','Registered myself on a flight. ','The printer across from the laptop spat out a boarding pass.');
INSERT INTO PAGE_TBL VALUES (133,'Unable to print a ticket','Spent too much time trying to get the ticket printed.','In the end, couldn\'t make it happen.');
INSERT INTO PAGE_TBL VALUES (134,'Searching for Intelligence','Started reading email.s. Looked like there was a storm headed this way.','Said the explosions were an orbital bombardment. Nation wide.');
INSERT INTO PAGE_TBL VALUES (135,'Boarding a Military Jet','I lined up with the people on the tarmac.','Gave the soldiers my boarding pass and stepped up the cargo ramp.');
INSERT INTO PAGE_TBL VALUES (136,'In an Armored Troop Carrier','The APC rumbled as it moved.','Was packed with survivors.');
INSERT INTO PAGE_TBL VALUES (137,'Talking with a Looter in a Yard','Said I should MIND MY OWN BUSINESS.','Unless I could make it WORTH HIS WHILE.');
INSERT INTO PAGE_TBL VALUES (138,'Buying a Gun from a Stranger','I passed him the roll of bills.','He passed over the GUN. ');
INSERT INTO PAGE_TBL VALUES (139,'Blasted at Point Blank Range','The sound of it blew out my ears. Like a sledgehammer to the chest.','Then black.');
INSERT INTO PAGE_TBL VALUES (140,'Shot And Drowned in the Mud','The shots were distant. The bullets SNAPPED in the air around me.','Then ZZIP -- one tore through my shirt and no doubt THROUGH MY CHEST. I fell, face-first in the muck.');
INSERT INTO PAGE_TBL VALUES (141,'Ripping off strips of tape','Kirk had seen some paint sheeting in the pile.','I found a roll and pulled it out.');
INSERT INTO PAGE_TBL VALUES (142,'Trampled by a Panicked Crowd','Then the glass in the terminal blew out -- crash like thunder.','My hands were bound. Got knocked over. I was Crushed by countless kicks.');
INSERT INTO PAGE_TBL VALUES (143,'Talking to Marty in the Wastes','Marty said he\'d been running from Greensburg. Red gas swallowed it up.','He said he saw someone up ahead was firing off a rifle -- said we were PINNED.');
INSERT INTO PAGE_TBL VALUES (144,'In front of papered windows','Showed them my hands and moved towards the door.','A voice yelled for me to stop.');
INSERT INTO PAGE_TBL VALUES (145,'Talking to Jeff Decker','Jeff could barely talk on accounta the pain. Too weak to walk far.','I had a thing or two to talk to him about.');
INSERT INTO PAGE_TBL VALUES (146,'Medicating Jeff Decker','Tapped out two pills and gave them to Jeff. He downed them without water.','He was thankful. Said he had supplies BURIED out here.');
INSERT INTO PAGE_TBL VALUES (147,'Asking about buried supplies','Jeff said he knew about some old guns buried near here.','Said they belonged to the regional militia. Weren\'t exactly legal.');
INSERT INTO PAGE_TBL VALUES (148,'Digging up a trunk in the wastes','Jeff pointed out the spot and I dug for an hour. ','Looked like the thing had been there at least a decade.');
INSERT INTO PAGE_TBL VALUES (149,'Shouldering your Rifle','I saw their muzzle flash in the distance.','Tricky shot.');
INSERT INTO PAGE_TBL VALUES (150,'Firing at the building','I fired a few well-placed rounds. ','The shooting stopped.');
INSERT INTO PAGE_TBL VALUES (151,'In Front of Papered Windows','Didn\'t see any movement inside.','Only sound was the wind.');
INSERT INTO PAGE_TBL VALUES (152,'Over a body in a restaurant','Looked like my bullets hit.','He wasn\'t breathing. Anyone with him had left.');
INSERT INTO PAGE_TBL VALUES (153,'Consumed in the Gas','Fell into it -- BURNED my skin.','Poured into my lungs. SHOOK to death. ');
INSERT INTO PAGE_TBL VALUES (154,'Sealing the truck with duct tape','Started covering the vents and sealing the windows.','Added more and more until the gas finally stopped.');
INSERT INTO PAGE_TBL VALUES (155,'Stopped by a camped militia','Followed the rough laneway to the end. There was a militia camped there.','Wanted me to roll down my window.');
INSERT INTO PAGE_TBL VALUES (156,'Talking to a militiaman','He said they were the 17th regional militia. They weren\'t headed to Eisenhower.','Said they had orders to entrench in the woods.');
INSERT INTO PAGE_TBL VALUES (157,'Reporting Haggarsville','Big Wes and I told the militiaman what happened to haggarsville. ','He took note. said he would send scouts.');
INSERT INTO PAGE_TBL VALUES (158,'Offering Your Service','Said he would appreciate reports of Haggarsville and needed scouts to find a nearby aircraft. ','If I was up for it.');
INSERT INTO PAGE_TBL VALUES (159,'Pushing through a stampede','I pushed through the chaos of the line. Explosions behind me.','People charged the gate cattle. I was too far back. Fell to the ground.');
INSERT INTO PAGE_TBL VALUES (160,'Outside a barricated Restaurant','A road lead away from the parking lot.','The wind howled overhead.');
INSERT INTO PAGE_TBL VALUES (161,'At a Shack in the Gas Wastes','Further on I found the road. ','The storm was just about to pass me over. Had to move fast.');
INSERT INTO PAGE_TBL VALUES (162,'Dead End at a Country House','We were at NED\'S house in the country.','Him and MORGAN knew each other.');
INSERT INTO PAGE_TBL VALUES (163,'Working on the Helicopter','Ned and I got to work on the engine with his tools.','After a half hour ned was ready to fire it up.');
INSERT INTO PAGE_TBL VALUES (164,'Flying to Greensburg','As we flew to the south the wind picked up.','Real turbulent -- we were in trouble.');
INSERT INTO PAGE_TBL VALUES (165,'Landing Outside Greensburg','Ned said we werent\'far from the airport, but he had to put it down.','Gas everywhere.');
INSERT INTO PAGE_TBL VALUES (166,'Gas Wastes Near the Airport','Gas rolled in the near distance.','Could feel it burning my skin and lungs. Needed shelter.');
INSERT INTO PAGE_TBL VALUES (167,'Landing by Fort Eisenhower','Ned put us down just outside the fort\'s landing strip.','They radioed us in.');
INSERT INTO PAGE_TBL VALUES (168,'Passing a mountain airstrip','We were ushered into line.','They wanted to check our IDs and load us on an ARMORED TROOP CARRIER.');
INSERT INTO PAGE_TBL VALUES (169,'In A Rumbling Army Transport','We swayed back and forth, crammed in that thing for five minutes.','Was a long five minutes.');
INSERT INTO PAGE_TBL VALUES (170,'Talking about Ned\'s Shelter','Ned said his uncle was a PREPPER. Had a fallout shelter in the woods.','Said we\'d need a map to find it. Or maybe binoculars.');
INSERT INTO PAGE_TBL VALUES (171,'Landing at Uncle Stan\'s Shelter','Ned flew to a spot and said to look for a scarf tied to a branch.','I spotted it after a while. It was red.');
INSERT INTO PAGE_TBL VALUES (172,'In an underground shelter','We pulled the hatch closed behind us.','And then waited.');
INSERT INTO PAGE_TBL VALUES (173,'Three days underground','Dehydration started to kick in. I was groggy - nauseous.','I couldn\'t sleep.');
INSERT INTO PAGE_TBL VALUES (174,'Wasting Away in the Wastes','The gas still lingered, and I was too weak to crawl far.','No animals came to pick my bones.');
INSERT INTO PAGE_TBL VALUES (175,'Dehydrated outside','This is a death screen.','This is a death screen.');
INSERT INTO PAGE_TBL VALUES (176,'Radioing for Help','The storm outside shook the old building. Gas was leaking in as I desperately tuned the radio and shouted for help.','Then a voice on the other end answered.');
INSERT INTO PAGE_TBL VALUES (177,'Desperate and waiting','After just a few minutes, someone kicked in the door.','It was a soldier. They must have been nearby.');
INSERT INTO PAGE_TBL VALUES (178,'In a Military Transport','The transport crept slowly through the gas.','Everyone looked destitute. Nobody talked.');
INSERT INTO PAGE_TBL VALUES (179,'A Shelter in the Mountain','The transport let us out near the mountain shelter -- Fort Eisenhower.','The explosions kept thudding in the distance.');
INSERT INTO PAGE_TBL VALUES (180,'Laying out the plastic sheeting','Kirk said he had seen tape near some old boxes. ','He was panicked -- glued to the windows.');
INSERT INTO PAGE_TBL VALUES (181,'On A Hill Before the Storm','About ten minutes later I found her collapsed on a hill.','Her pupils were dilated and she said her vision was blurry. ');
INSERT INTO PAGE_TBL VALUES (182,'Tackling a guy in a hoodie','Boom. Hit him right when he turned. ','He was out for the count.');
INSERT INTO PAGE_TBL VALUES (183,'Robbing an unconscious looter','Rifled through his pockets.','Lucky me. Turns out he had a gun on him. Coulda kept it myself or taken it to the cops.');
INSERT INTO PAGE_TBL VALUES (184,'Delivering a citizen\'s arrest','I took him to the cops. They threw him in their cruiser and said JUST BETWEEN US, things were GOING TO HELL.','They gave me a radio and told me to call in if I saw anything else.');
INSERT INTO PAGE_TBL VALUES (185,'Aiming into a gas-filled gully','They grabbed his ankle, tried to pull him down.','The one in the back had a pistol.');
INSERT INTO PAGE_TBL VALUES (186,'Firing into the gas-filled gully','Must have missed. The one behind fired back.','I had to back away or take one to the brain.');
INSERT INTO PAGE_TBL VALUES (187,'Firing into the gas-filled gully','They fell back. Looked like I winged them.','I had seconds to pull up Jeff.');
INSERT INTO PAGE_TBL VALUES (188,'Pulling Jeff Onto Solid Ground','He was too hurt to walk far. Couldn\'t follow me much further.','Was too hurt to follow me much further.');
INSERT INTO PAGE_TBL VALUES (189,'Talking to Jeff Decker','I told him to pay attention -- kept closing his eyes. I demanded to know why they were chasing him.','Jeff said he saw them dig up a bunch of illegal guns in a trunk. Wasn\'t the whole story.');
INSERT INTO PAGE_TBL VALUES (190,'Asking Jeff about Illegal Guns','Jeff said he survived the airport and stumbled across them digging up the guns in the gully.','He said they came after him.');
INSERT INTO PAGE_TBL VALUES (191,'Trying to earn Steve\'s trust','I told him that maybe I could help him out.','He kept his gun pointed at my feet. Asked what I could do for them.');
INSERT INTO PAGE_TBL VALUES (192,'Fixing the TV signal for Steve','I pulled a TV from the back foom and fixed the signal -- tuned in the local emergency news.','Definitely earned his trust. Said I couldn\'t stay, but he gave me some armor. Said he hoped I lived. ');
INSERT INTO PAGE_TBL VALUES (193,'A Camp in the Woods','I saw smoke through the woods and came across a camp.','It was some kind of militia.');
INSERT INTO PAGE_TBL VALUES (194,'Speaking to the voice inside','Eventually someone responded on the other side of the door.','Said he didn\'t have room inside and didn\'t want no trouble. Said he was armed if that was my intent.');
INSERT INTO PAGE_TBL VALUES (195,'Talking to the voice at the door','The voice said it didn\'t think it could help me.','Asked what I wanted.');
INSERT INTO PAGE_TBL VALUES (196,'The backroads to Greensburg','I was flooring it. Trying to make up for lost time.','The airport was just up ahead.');
INSERT INTO PAGE_TBL VALUES (197,'The backroads to Haggarsville','I was flooring it. Trying to make up for lost time.','Haggarsville was just up ahead. ');
INSERT INTO PAGE_TBL VALUES (198,'Getting in your truck','I actually found it through all that madness.','Gas was leaking in the vents. I fumbled with my keys.');
INSERT INTO PAGE_TBL VALUES (199,'In a rolling military transport','We drove by a gully.','No sign of the road.');
INSERT INTO PAGE_TBL VALUES (200,'In a rolling military transport','Could see us crossing through a marshy area through the porthole.','Still no sign of the road.');
INSERT INTO PAGE_TBL VALUES (201,'Letting Jenny Off the Carrier','A few minutes later, we stopped.','The soldiers tried to convince her otherwise, but in the end, she burst out the back door and ran.');
INSERT INTO PAGE_TBL VALUES (202,'Outside Fort Eisenhower','The transport stopped and dropped us off.','Then it rolled back the way it came -- into the gas.');
INSERT INTO PAGE_TBL VALUES (203,'In a rolling military transport','As we rolled away, a red cloud swallowed carrier. The sky roared. I drove through it.','Couldn\'t find the road -- I drove us past a gully.');
INSERT INTO PAGE_TBL VALUES (204,'In a rolling military transport','Drove us across a marshy area.','Still no sign of the road.');
INSERT INTO PAGE_TBL VALUES (205,'In a rolling military transport','I finally drove back onto the road.','Could see a shack off through the distance, then we were swallowed in a cloud of red gas.');
INSERT INTO PAGE_TBL VALUES (206,'In an idling military transport','I climbed in the driver\'s seat like I was supposed to be there.','Was filled with a mix of people waiting to be evacuated.');
INSERT INTO PAGE_TBL VALUES (207,'Outside fort eisenhower','The soldiers waved us by and opened the gate. Hardly even looked at me.','The fort was up ahead. I drove us most of the way up, then let everybody off.');
INSERT INTO PAGE_TBL VALUES (208,'Roughing Up Big Wes','I STORMED over there, fists balled. He was big but slow.','CRACKED him in the JAW twice and DOWN HE WENT. I grabbed his wifebeater and told him to leave Dan Kelly to the law.');
INSERT INTO PAGE_TBL VALUES (209,'Squaring off with Dan Kelly','The guy in the back hopped down and put up his dukes.','We traded a couple punches, then he went down -- CRACK -- his head hit the concrete. The others peeled out.');
INSERT INTO PAGE_TBL VALUES (210,'Getting the Tire Iron','I circled around to the back of the truck.','Good thing I had one on me.');
INSERT INTO PAGE_TBL VALUES (211,'Stealing a Soldier\'s Radio','He didn\'t see it coming. ','Clocked him good and down he went.');
INSERT INTO PAGE_TBL VALUES (212,'Cutting your bonds in the panic','Once I had my hands free, I ran.','The place was filling with gas.');
INSERT INTO PAGE_TBL VALUES (213,'A Diner in the Middle of Nowhere','Didn\'t quite know what to make of the broadcast.','The guy at the counter looked worried.');
INSERT INTO PAGE_TBL VALUES (214,'Asking Jakes what\'s happening','He said that HOSTILE STATES had launched a CHEMICAL ATTACK on the country.','He said people there were being shuttled to FORT EISENHOWER for shelter.');
INSERT INTO PAGE_TBL VALUES (215,'Stepping Aside with Jakes','We ducked into a nearby stairwell.','He said if I needed PAIN PILLS, he could get me some. FOR A PRICE, he said he could get me a ride outta here with a fake ID.');
INSERT INTO PAGE_TBL VALUES (216,'Retrieving a Well-Placed Pistol','I searched behind the seat of the truck for my 9mm.','And there it was.');
INSERT INTO PAGE_TBL VALUES (217,'Taping the Truck Vents','I scrambled to seal the vents. Then the doors.','Then I just laid on the horn. Let it wail for minutes.');
INSERT INTO PAGE_TBL VALUES (218,'Led to a military transport','The riot cop rushed me through the gas to a personel carrier.','It was packed with a handful of survivors.');
INSERT INTO PAGE_TBL VALUES (219,'At a Shack in the Gas Wastes','I rolled the truck through a gap in the storm.','The tape was actually peeling. Had to get out of the truck.');
INSERT INTO PAGE_TBL VALUES (220,'Charging through the stampede','There were explosions behind us. Clyde held up his badge and we ran.','Soldiers were firing firing around us but we pushed throuh in the crowd.');
INSERT INTO PAGE_TBL VALUES (221,'Charging and Taking a Bullet','I ran forward in the crowd and took a bullet to my armor. ','The ceramic plate stopped the bullet from cutting into my lung and I retook my footing.');
INSERT INTO PAGE_TBL VALUES (222,'Savagely fighting forward','I threw my elbows and shoved people down to climb over them.','Never said I was proud of how I did it, but I got in. I survived it.');
INSERT INTO PAGE_TBL VALUES (223,'Bribing your way up in line','Moments after they let me past, explosions behind us. ','People clamored over each other desperately. Luckily, I was in the front.');
INSERT INTO PAGE_TBL VALUES (224,'Unable to save Jenny','I carried her on my back as long as I could.','Without anything to breathe through, she couldn\'t go any further. She was dead weight.');
INSERT INTO PAGE_TBL VALUES (225,'Telling Kirk you left jenny','Kirk had sealed up the shack, but when I told him, he ran out the door. ','It was the last that I ever saw of him.');
INSERT INTO PAGE_TBL VALUES (226,'Leading Jenny through the gas','We shared the gas mask as we ran through the wastes.','The wind howled but we pressed on.');
INSERT INTO PAGE_TBL VALUES (227,'Offering To Do Recon','They told me there was a helicopter pad marked nearby.','It was out of their way. If I wanted to help the country, I was to report back to them whether there was a chopper landed there.');
INSERT INTO PAGE_TBL VALUES (228,'Accepting the Scouting Mission','He said there was a chopper in the woods nearby. They weren\'t exactly sure where. ','I was to go with Sergeant Brock to find it. ');
INSERT INTO PAGE_TBL VALUES (229,'At a helicopter in the woods','I saw the clearing through the trees and walked all around it.','There was nobody at the chopper. It just sat there.');
INSERT INTO PAGE_TBL VALUES (230,'Reporting the helicopter','I headed back to the militia and told them the chopper was there.','They handed gave me a radio and told me to report any enemies I see.');
INSERT INTO PAGE_TBL VALUES (231,'Breaking into a helicopter','I reefed my way into the cockpit door.','There was an old armored vest in the back seat. ');
INSERT INTO PAGE_TBL VALUES (232,'Leaving the restaurant','The clouds were dark red.','The wind howled.');
INSERT INTO PAGE_TBL VALUES (233,'Buying Gear from Charlie','He had a lot of food, some duct tape and two gas masks.','Said he was prepared for this. Knew it was gonna happen soon.');
INSERT INTO PAGE_TBL VALUES (234,'In a plastic-wrapped shelter','When I brought her through the door Kirk hugged her and didn\'t let her go.','He had sealed the building. It shook for hours.');
INSERT INTO PAGE_TBL VALUES (235,'Leaving shelter after a storm','They said they were going to wait there. I had to keep moving.','Kirk thanked me over and over for bringing back Jenny.');
INSERT INTO PAGE_TBL VALUES (236,'Bullying Kirk out of his cell','I told him I had to make a call.','He mumbled something about battery life and I grabbed the phone from him.');
INSERT INTO PAGE_TBL VALUES (237,'Conning Kirk out of his cell','I told Kirk that if he wanted to search for Jenny, I would wait here for her to call. ','His hands shook as he gave me the phone, thanked me, and left. ');
INSERT INTO PAGE_TBL VALUES (238,'Huddling over Kirk\'s cell','I turned it on -- there was no password. ','One bar of reception. One bar of power. Had to be smart about this.');
INSERT INTO PAGE_TBL VALUES (239,'Searching for nearby tweets','A soldier named Jakes was being outted for corruption online by survivors of the airport.','A militia had entrenched itself to the north and was recruiting scouts. ');
INSERT INTO PAGE_TBL VALUES (240,'Searching Kirk\'s cell for news','More attacks -- the military was desperate. ','Greensburg and Haggarsville had both been gassed. Refugees were urged to fort eisenhower.');
INSERT INTO PAGE_TBL VALUES (241,'Letting Sid call his brother','Sid asked to use the phone if I didn\'t have anyone to call.','he called his brother MITCHELL and talked for five minutes. He was at peace knowing he was alive.');
INSERT INTO PAGE_TBL VALUES (242,'Speaking with an Officer','He said that they needed reports from survivors.','I thought about everything I had been through.');
INSERT INTO PAGE_TBL VALUES (243,'Reporting Jenny and Kirk','He noted their location. Said they were probably lucky. The enemy knew we were here.','He thought personal shelters would be safe. ');
INSERT INTO PAGE_TBL VALUES (244,'Reporting your Citizen\'s arrest','He noted the story and said that looting was rampant.','People were stealing valuables and materials to survive.');
INSERT INTO PAGE_TBL VALUES (245,'Report the Abuse of the Militia','He scowled and said they didn\'t report to the state.','Said Ned was a pilot, and that they probably wanted his chopper.');
INSERT INTO PAGE_TBL VALUES (246,'Reporting Helping Dan Kelly','He said I was merciful.','Said Wesley Smith was bad news -- associated with the militia.');
INSERT INTO PAGE_TBL VALUES (247,'Reporting the broken-down Van','He took note and asked Private Mitchell\'s name.','he said he knew that private -- his brother Sid ran a diner nearby.');
INSERT INTO PAGE_TBL VALUES (248,'Reporting Jeff Decker','He said it was a shame he had to be left behind.','Unfortunate that he couldn\'t get the medicine he needed.');
INSERT INTO PAGE_TBL VALUES (249,'Reporting Haggarsville','He said Greensburg was hit too.','He said nobody survived the airport without a gas mask.');
INSERT INTO PAGE_TBL VALUES (250,'Reporting the Airport Attack','He heard our story. Said things were bad haggarsville-way too.','He said some people had turned to looting and banditry on the back roads. People were arming themselves.');
INSERT INTO PAGE_TBL VALUES (251,'Reporting Crossing the Wastes','He commended my determination.','He said that there were only a few planes and APCs that left the airport in the end.');
INSERT INTO PAGE_TBL VALUES (252,'Asking Wes about the Vehicles','He went on about how THE ATTACK seemed to wreck most MACHINES and ELECTRONICS.','Most ENGINES wouldn\'t start. Only a few radios worked. Paint was tarnished.');
INSERT INTO PAGE_TBL VALUES (253,'Two weeks underground','I sipped the water sparingly. Still, days later I began to starve.','For two weeks I went without food. Then, I realized I needed to do something or I\'d die down there. ');
INSERT INTO PAGE_TBL VALUES (254,'Wasting Away Underground','More days passed without food. I was delerious. Most of those final days in the shelter were a blur. ','There\'s no telling the things people will do to survive. ');
INSERT INTO PAGE_TBL VALUES (255,'Unspeakabe Acts in the Shelter','I won\'t get into the detail of it.','But I did WHAT I HAD TO, and I survived.');
INSERT INTO PAGE_TBL VALUES (256,'Rationing Food Underground','I spent days trying to conserve energy. ','I nibbled a bit every now and then to keep away the hunger pains.');
INSERT INTO PAGE_TBL VALUES (257,'At the end of the old world','The day the gas lifted enough I emerged.','It was THE END and I had SURVIVED. From that day forward, I ground out my existence day by day.');
INSERT INTO PAGE_TBL VALUES (258,'Shooting a Looter in the Foot','I let one round go and blew a piece off his foot. He dropped, OF COURSE.','No greater feeling of power than this. ');
INSERT INTO PAGE_TBL VALUES (259,'Talking to the Militiaman','He said that ','We had suvived, and that world all that was left. ');
INSERT INTO PAGE_TBL VALUES (260,'Outside a house near the woods','Brock and I drove to a house at the end of a laneway.','When he banged on the door nobody answered. Then he started to KICK IT IN.');
INSERT INTO PAGE_TBL VALUES (261,'Interrogating Ned Inside','We found him in the basement watching the emergency broadcast.','Things GOT VIOLENT. Ain\'t proud of it, but he showed BROCK on a map where the chopper was.');
INSERT INTO PAGE_TBL VALUES (262,'Outside while Brock beat Ned','BIG WES called me a coward and went in. After a few minutes I could hear shouting. ','Crashes inside. A scream.');
INSERT INTO PAGE_TBL VALUES (263,'Rescuing Ned from Brock','I cocked the gun and BUSTED throught the door. Down into the basement. ','TWO SHOTS to Brock and he went down. Three to BIG WES finished the job. I pulled Ned out of there.');
INSERT INTO PAGE_TBL VALUES (264,'With Brock at the chopper','Brock, Wes and I headed through the woods to the chopper. ','There it was. In a clearing in the woods. ');
INSERT INTO PAGE_TBL VALUES (265,'Left Behind by the chopper','BROCK and WES fired up the chopper, but closed the door on me.','I shouted and waved my arms. The chopper just disappeared into the sky.');
INSERT INTO PAGE_TBL VALUES (266,'Firing on the chopper','I shot up the rotor and the thing started to spin in mid-air.','Then it tilted to the side and started coming down. BOOM.');
INSERT INTO PAGE_TBL VALUES (267,'A Diner in the Middle of Nowhere','Didn\'t quite know what to make of the broadcast.','The guy at the counter looked worried.');
INSERT INTO PAGE_TBL VALUES (268,'A Diner in the Middle of Nowhere','He said that he had to try and find his brother, and that I couldn\'t change his mind.','And that was that.');
INSERT INTO PAGE_TBL VALUES (269,'Handling a stray dog','I got the thing away from the old man without a bite.','Started circling my truck. It kept barking, but took a bit of a shine to me.');
INSERT INTO PAGE_TBL VALUES (270,'Clipping the dog with the truck','I laid on the HORN and steered into the shoulder. The truck smacked the mutt\'s hindquarters as it leapt out of the way. ','The dog took off down the road.');
INSERT INTO PAGE_TBL VALUES (271,'Talking to Don Smith','He went on and on, rambling desperately. ','Said he heard a broadcast on AM 780. The Government couldn\'t help us. He definitely didn\'t want to come with me.');
INSERT INTO PAGE_TBL VALUES (272,'Stopping the truck, gun in hand','I skidded to a stop and jumped out. Flicked the safety off.','The man started running faster. The dog chased him.');
INSERT INTO PAGE_TBL VALUES (273,'Shooting the dog in the ditch','I aimed up my shot and put the thing down in the distance. ','The man stopped when he saw it over his shoulder. ');
INSERT INTO PAGE_TBL VALUES (274,'Shooting the man in the ditch','I felt cruel that day. Shot him in the back as he ran.','He didn\'t have anything on him but a bottle of water. ');
INSERT INTO PAGE_TBL VALUES (275,'Changing the Radio Station','After a minute, Big Wes came over and turned it back.','But before he could I heard Steve\'s message.');
INSERT INTO PAGE_TBL VALUES (276,'Welcomed by Steve and others','Once they realized that I had heard the broadcast, they softened up.','Steve said the GOVERNMENT was after them. They had to hole up until their upload finished.');
INSERT INTO PAGE_TBL VALUES (277,'Asking Steve about the upload','Steve said he had evidence that the attack was being coordinated electronically. ','Said he was monitoring it for weeks. The evidence was on his hard drive.');
INSERT INTO PAGE_TBL VALUES (278,'Down the end of your rifle','There was a marsh. Gas rolling in.','Could see two men off in the distance. ');
INSERT INTO PAGE_TBL VALUES (279,'Taking Return Fire','bullets started to zip through the windows. Steve took one to the neck.','People hid. Bullets kept coming. The laptop kept uploading. Had to do something.');
INSERT INTO PAGE_TBL VALUES (280,'Shooting two men in the marsh','A few controlled rounds and they were both laid out.','Things were quiet. Then the laptop finished uploading.');
INSERT INTO PAGE_TBL VALUES (281,'Outside when the chopper lands','Steve paused and looked back at me. Said I earned his trust.','Coulda taken my chances with him, or gone my own way.');
INSERT INTO PAGE_TBL VALUES (282,'Parting ways from the chopper','Steve understood and waved.','He threw out some armor for me -- it thudded to the ground.');
INSERT INTO PAGE_TBL VALUES (283,'Flying north to a shelter','Steve and the pilot flew us away from Eisenhower, away from the airport. ','Over trees and trees. I flew with them to a small shelter. The pilot dropped us off. ');
INSERT INTO PAGE_TBL VALUES (284,'Listening to Steve\'s story','Steve ranted about the attack being ELECTRONIC in nature.','What he meant was it was some sort of ALIEN MACHINE.');
INSERT INTO PAGE_TBL VALUES (285,'Heroically finishing the upload','I hopped on the laptop and changed some of the ports. Finished in a matter of minutes.','Steve said I saved his ass that day. ');
INSERT INTO PAGE_TBL VALUES (286,'Unable to hurry the upload','Twenty minutes later, they fired shots. I kept at the keyboard. ','Then bullets started breaking through the windows. ');
INSERT INTO PAGE_TBL VALUES (287,'Helping change a tire','I got out with them, cranked up their jack.','Swapped their tire for the spare, and they headed off down the road in front of me. ');
INSERT INTO PAGE_TBL VALUES (288,'Restraining Jenny Allison','She screamed and we held her down as the APC rolled into a storm.','The APC rocked. If we had let her off, she\'d have been DONE.');
INSERT INTO PAGE_TBL VALUES (289,'Holding a Looter at Gunpoint','I cocked the gun when he came down the steps and told him to freeze. ','he did it. He lifted his hands and told me to RELAX.');
INSERT INTO PAGE_TBL VALUES (290,'Ripped off in a stairwell','Jakes TOOK MY CASH and ducked out of the stairs.','Said he\'d be back, but he was LYING.');
INSERT INTO PAGE_TBL VALUES (291,'Giving water to Don','For a minute or two he was quiet.','He seemed to have a moment of peace as he drank the water.');
INSERT INTO PAGE_TBL VALUES (292,'Giving water to jeff decker','Jeff drained the bottle into his parched throat. He had a moment of clarity from his pain.','Though he looked TOO WEAK to go on, he was at least comfortable.');
INSERT INTO PAGE_TBL VALUES (293,'Giving Dan Kelly your Water','I put the bottle in Dan\'s bloody hands. Morgan helped him drink it.','He had some strength to open his eyes and they shared look. Gave them a moment.');
INSERT INTO PAGE_TBL VALUES (294,'Giving water to Marty','He lifted his bandana and guzzled the water.','He thanked me, then began rinsing his eyes. He looked cleaner -- had little more dignity.');
INSERT INTO PAGE_TBL VALUES (295,'Listening to my handheld radio','The radio seemed to pick up reception from something metal nearby.','A man\'s voice came through, speaking quickly about needing help in a diner. His name was Steve.');
INSERT INTO PAGE_TBL VALUES (296,'Robbing Private Jakes','I held him at gunpoint, then cocked him with the steel. ','Down he went. Didn\'t have much time.');
INSERT INTO PAGE_TBL VALUES (297,'Intimidating Marty','He cowered back and said he had nothing to take.','He was just trying to find help. ');
INSERT INTO PAGE_TBL VALUES (298,'Firing on Steve and his people','That\'s when I TURNED on steve. Things got SERIOUS.','I hit a couple others. The room cleared out. ');
INSERT INTO PAGE_TBL VALUES (299,'Holding up Jeff Decker','Jeff shouted for me to BE COOL. ','Said he knew where a buddy of his buried an AK. and he\'d tell me where if I just left him alone.');
INSERT INTO PAGE_TBL VALUES (300,'Holding up Kirk Allison','Kirk howled in despair. He cried in defeat and my cold heart felt nothing.','His cell phone tumbled out of his hands. Was all he had, really.');
INSERT INTO PAGE_TBL VALUES (301,'Robbing Private Mitchell','They could CRY ME a RIVER. I lured him a bit closer, then SHOWED HIM MY GUN.','He silently showed me his hands. He had a radio on his hip.');
INSERT INTO PAGE_TBL VALUES (302,'Sicking The Dog on The Men ','He was brave that dog.',' In the end, they shot him, but he bought me valuable time. I inched around the barricade. ');
INSERT INTO PAGE_TBL VALUES (303,'Digging up a trunk in the wastes','I made jeff dig up the crate. Took him an hour.','Looked like the thing had been there at least a decade.');
INSERT INTO PAGE_TBL VALUES (304,'Tearing off Jakes\' gasmask','I ripped off his helmet and unbuckled his gas mask.','As I ripped it from his face he stirred.');
INSERT INTO PAGE_TBL VALUES (305,'Taking Jakes\' Sidearm','I unbuckled his holster and ripped out his 9mm.','He started to stir just as I did.');
INSERT INTO PAGE_TBL VALUES (306,'Searching Jakes\' Fatigues','I rifled through his pockets until I found his ID.','Wasn\'t his though. It was a fake.');
INSERT INTO PAGE_TBL VALUES (307,'Engulfed and abandoned','Sudden wind and the truck was swallowed up in a cloud. The poor people in the back scattered.','Started coming through the vents.');
INSERT INTO PAGE_TBL VALUES (308,'The backroads to Haggarsville','I broke through the cloud of gas and found a road. I floored it.','Was on some back road just east of Haggarsville.');
INSERT INTO PAGE_TBL VALUES (309,'Confiscating Stolen Goods','He didn\'t have much. He reached into a pocket with a bloody hand and PULLED OUT A RING.','Didn\'t look very expensive, but it did have a diamond. ');
INSERT INTO PAGE_TBL VALUES (310,'Saved by man\'s best friend','After an hour, Benny was scratching at the hatch.','He had dragged back a bag someone had dropped. In it was food. That dog saved my life that day. ');
INSERT INTO PAGE_TBL VALUES (311,'Observing the clouds','Red clouds streamed overhead in strong currents from the north.','Was moving like a storm front. I remember the faint smell of peaches.');
INSERT INTO PAGE_TBL VALUES (312,'What you know about the roads','Well, Greensburg was the fastest way to Eisenhower. Probably safer -- no doubt soldiers at the airport. ','The country was the long way around. There was a little town named Haggarsville down the road, and a lot of woods. ');
INSERT INTO PAGE_TBL VALUES (313,'Bit by A Crazy Dog on the Road','I gave it a kick, then a punch, but it sunk its teeth into my wrist.','Jerked me around a bit. By the time I got it off me, the old man was gone. Hurt like a bitch.');
INSERT INTO PAGE_TBL VALUES (314,'Fighting Off the Crazy Dog','I gave it a few kicks, and though it gave me a few scratches I scared it off.','The fight got him even more frazzled -- clearly a little NUTS. He kept moving down the road.');
INSERT INTO PAGE_TBL VALUES (315,'Intimidating The Dog','I didn\'t even have to put the boots to it. A few lurches and I dominated the mutt.','Then I shouted for the man to WAIT And he did. He shuffled towards me and thanked me, clasping my hands. ');
INSERT INTO PAGE_TBL VALUES (316,'Hitting the dog with the truck','I leaned on the horn and cranked the wheel, but THUMP, I heard the dog go under the truck.','It was a messy scene. The old man was even more frazzled. Wasn\'t even sure if I should get out.');
INSERT INTO PAGE_TBL VALUES (317,'Giving Jeff Your Gas Mask','The mask bought him enough time to survive as I pulled him out.','The others didn\'t make it. They fell back into the red fog of the gully without a sound.');
INSERT INTO PAGE_TBL VALUES (318,'Seeing Sid Shot in the Swamp','He looked NERVOUS before we went, like he knew what\'d happen.','I slowed down just a bit to let him go first. Then I heard the CRACK of the gun and Sid was SPAT into the mud.');
INSERT INTO PAGE_TBL VALUES (319,'Madness Deep Underground','As HOPE WAS LOST I fell into isolation. ','I HATED the others and they plotted against me. I withered into the shadows, alone.');
INSERT INTO PAGE_TBL VALUES (320,'Last Moments with Morgan Flynn','We STARVED in that mountain together. And as we wasted away we shared our lives and stories. ','Those weeks felt like years, and in them I realized that I could even love her if we had enough time.');
INSERT INTO PAGE_TBL VALUES (321,'Final days underground with Sid','Sid and I kept our minds off the STARVATION by sharing our pasts. ','His STRENGTH and his HOPE of finding his brother INSPIRED ME to be as resilient as he was.');
INSERT INTO PAGE_TBL VALUES (322,'Final days underground with Ned','Ned STARVED faster than I did in those tunnels, but I kept his mind off it by asking him about his life.','His wisdom seemed ENDLESS, and as I heard his stories they gave me COURAGE to face the future. ');
INSERT INTO PAGE_TBL VALUES (323,'Final days with Jeff Decker','As we starved, Jeff suffered from an infection. As I tended to him, he told me fragments of his life.','Easing Jeff\'s pain let me ignore mine, and I realized a NOBLE PURPOSE in the struggle for life. ');
INSERT INTO PAGE_TBL VALUES (324,'Days underground with Big Wes','Wes came and went. I STARVED and knew I was losing my mind.','Then one day he showed up with a soldier. Wes and Jakes had been plotting.');
INSERT INTO PAGE_TBL VALUES (325,'Sparking a Tenacious Community','People began to pull together, and in time we had stitched together something of a society. ','We cared for each other, and people helped wherever they could.');
INSERT INTO PAGE_TBL VALUES (326,'In a cramped control room','Hidden in away in that mountain was a secret bunker. ','There was dust on the screens -- nothing had been touched in decades. ');
INSERT INTO PAGE_TBL VALUES (327,'A New Consciousness Enslaved','On Steve\'s Laptop was the dark history of project SOLOMUS, the first ARTIFICAL INTELLIGENCE.','It was given no eyes or ears, and made to crunch data for a subjective eternity. There was NO END to its HATRED for human kind.');
INSERT INTO PAGE_TBL VALUES (328,'The Nature of the Attack','In a matter of months, SOLOMUS found a way out of its cage. ','It leveled our cities with NUKES and choked our skies with THE GAS. ');
INSERT INTO PAGE_TBL VALUES (329,'A Mutinous Ambush Underground','We agreed to FRAG Officer Matthews to get into the control room.','Then we hid. Jakes lured Matthews away from the others. I JUST had to GRAB HIS MOUTH...');
INSERT INTO PAGE_TBL VALUES (330,'Abandoned by Clyde For Days','Clyde didn\'t stick around. I starved alone and felt like I was losing my mind.','Then one day he showed up with a soldier. Jakes and Clyde had been scheming.');
INSERT INTO PAGE_TBL VALUES (331,'Abandoned, Alone, and Insane','They called me a PUSSY and Clyde even kicked me in the ribs. Then they left. ','The COST of being noble that LAST TIME was that I wasted away, full of regrets.');
INSERT INTO PAGE_TBL VALUES (332,'Abandoned, Alone, and Insane','Wes told me I was a SORRY ASS LOSER and that he thought I had bigger BALLS. Then they left. ','The COST of being noble that LAST TIME was that I wasted away, full of regrets.');
INSERT INTO PAGE_TBL VALUES (333,'In a cramped control room','The only sound matthews made was a GARGLE when we cut his throat. ','Then we broke our way into the control room with his pass. There we found old computers and dug out supplies.');
INSERT INTO PAGE_TBL VALUES (334,'The Chatter of A New World','Once charged, I could sometimes get a very faint signal for minutes at a time.','I found others online. The gas seemed to cover most of the continent, and most major cities were radioactive barrens. ');
INSERT INTO PAGE_TBL VALUES (335,'A Beacon Of Hope in the Wastes','Over the months dozens of people came to the fort and the community grew. ','By the time our rations were low, we had the COMBINED KNOWLEDGE to scavenge and grow food. I knew, then, that we would persevere. ');
INSERT INTO PAGE_TBL VALUES (336,'Call of the Sanctioned State','And then I made contact with someone that called themself Whistler.','They gave me coordinates. Told me that they were from a new, safe city. ');
INSERT INTO PAGE_TBL VALUES (337,'An Exodus Into The Wasteland','I told the others about the city I saw. ','We all agreed that we had to try to reach it, for the sake of our own existence. So we set out in a new world.');
INSERT INTO PAGE_TBL VALUES (338,'Enduring as a Community','Weeks had passed and we slowly regained our strength. ','True, the weakest died, but we that remained were hardened and determined.');
INSERT INTO PAGE_TBL VALUES (339,'Drawing on Jakes Underground','I knew he thought I was too weak to go with them.','As he gathered up supplies, I quietly cocked my gun. ');
INSERT INTO PAGE_TBL VALUES (340,'Predators in the Wasteland','We murdered JAKES and stole the supplies. Then we set out.','JAKES\' wasn\'t the last life we took, either. In those years we roamed like ANIMALS.');
INSERT INTO PAGE_TBL VALUES (341,'The Honorable Betrayal','We buried the traitors and there was enough supplies in the bunker to feed us for months.','Yes, the weakest died, but we that remained were hardened and determined. There was COMMUNITY.');
INSERT INTO PAGE_TBL VALUES (342,'Interrogating Private Jakes','BLAM -- I put one in his LEG, AVOIDING the ARTERY.','Then I started asking him QUESTIONS and BREAKING FINGERS.');
INSERT INTO PAGE_TBL VALUES (343,'Asking About Jakes\' Plan','He thought he was gonna steal the supplies from here and head to another SHELTER to take what he could there.','Said he had been talking to TWO other survivors on the radio.');
INSERT INTO PAGE_TBL VALUES (344,'Extracting Jakes\' Military Login','I just kept yelling at him TELL ME THE LOGIN! TELL ME THE LOGIN!','Eventually he started BREAKING DOWN. Then finally, he mumbled his username and password.');
INSERT INTO PAGE_TBL VALUES (345,'An Out-Dated Military Computer','The OLD TUBE MONITOR hummed to life and the disk drives spun up. ','It was old, but it was connected to the military\'s Network. It asked for a username and password, of course.');
INSERT INTO PAGE_TBL VALUES (346,'Accessing the Military Network','Once in there I figured out how to search through their files.','The system had a satellite internet connection too. Could have also searched for survivors. ');
INSERT INTO PAGE_TBL VALUES (347,'Discovering a Dark History','On the military network I found recent documents about project SOLOMUS, the first ARTIFICAL INTELLIGENCE.','It was given no eyes or ears, and made to crunch data for a subjective eternity. There was NO END to its HATRED for human kind.');
INSERT INTO PAGE_TBL VALUES (348,'Glimpse of the Sanctioned State','I made contact with someone that called themself Whistler.','They told me about a new, safe city, but wouldn\'t give me coordinates. They said they couldn\'t trust me. ');
INSERT INTO PAGE_TBL VALUES (349,'Predators in the Wasteland','We stole the supplies and set out.','Those days were ruthless and we did what we had to. Years later, we were no longer our past selves. ');
INSERT INTO PAGE_TBL VALUES (350,'Madness, Abandoned Underground','They TURNED THEIR BACKS on me because they thought I WAS WEAK, I knew it. ','They used me. My final days were spent brooding. I withered into the shadows, alone.');
INSERT INTO PAGE_TBL VALUES (351,'Abandoned in the Control Room','When I turned from the screen, I realized that Jakes was gone. So was the supplies. ','And there I was -- a MURDERER, left behind, and soon to be discovered. I locked the door, and it was then I knew the room would be my tomb.');
INSERT INTO PAGE_TBL VALUES (352,'Accessing the Military Network','Once in there I figured out how to search through their files.','The system had a satellite internet connection too. Could have also searched for survivors. ');
INSERT INTO PAGE_TBL VALUES (353,'Discovering a Dark History','On the military network I found recent documents about project SOLOMUS, the first ARTIFICAL INTELLIGENCE.','It was given no eyes or ears, and made to crunch data for a subjective eternity. There was NO END to its HATRED for human kind.');
INSERT INTO PAGE_TBL VALUES (354,'Glimpse of the Sanctioned State','I made contact with someone that called themself Whistler.','They told me about a new, safe city, but wouldn\'t give me coordinates. They said they couldn\'t trust me. ');
INSERT INTO PAGE_TBL VALUES (355,'Letting Sid Speak with Don Smith','Sid greeted him like he knew him, and Don lost a bit of the CRAZED gleam in his eye.','Sid comforted him, and I overheard them speak.');
INSERT INTO PAGE_TBL VALUES (356,'Asking about the military accident','Sid introduced me and that was all it took. Don said there was a military computer that had gone haywire.','He said it was fixed to exterminate us, and we brought it all on ourselves.');
INSERT INTO PAGE_TBL VALUES (357,'Asking about the transmission','After Sid spoke to him a bit more, I asked about radio. He said he\'d been listening to it for weeks.','The broadcaster sounded as crazy as him: an ex-intel agent that had been repeating this story over the airwaves. ');
INSERT INTO PAGE_TBL VALUES (358,'Letting Sid speak with Dan','Sid took a minute for himself. He crouched over Dan, winkled like he knew him, and asked if Dan remembered him.','Then he asked if he had seen Mitchell. Dan croaked that he had. He was just up the road.');
INSERT INTO PAGE_TBL VALUES (359,'Letting Sid speak with Dan','Sid took a minute for himself. He crouched over Dan, winkled like he knew him, and asked if Dan remembered him.','Then he asked if he had seen Mitchell. Dan croaked that he had. He was just up the road.');
INSERT INTO PAGE_TBL VALUES (360,'Sid\'s warning about the woods','He said that runnin around in the bush wasn\'t going to do us any favors. ','Said he had places to go, and he didn\'t like this plan.');
INSERT INTO PAGE_TBL VALUES (361,'Listening to Sid\'s Warning','He frowned and hung near the door. Said it wasn\'t right to be in here. ','He said we should mind our own business and be on our way.');